# Generated by Django 3.2.8 on 2021-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_channel_history_song_watchlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='images/%Y/%m/%d/'),
        ),
    ]
