# Generated by Django 3.2.8 on 2021-10-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_usermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(default='', upload_to='images/music'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='music'),
        ),
    ]
