# Generated by Django 3.2.8 on 2021-10-28 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20211027_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 5, 2, 25, 399891)),
        ),
    ]
