# Generated by Django 3.2.6 on 2021-11-14 02:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0008_auto_20211111_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.ManyToManyField(related_name='like_song', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 7, 40, 1, 164258)),
        ),
    ]
