# Generated by Django 3.2.6 on 2021-11-14 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20211114_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 10, 39, 29, 233769)),
        ),
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.usermodel'),
        ),
    ]
